# Generated by Django 4.0.5 on 2023-07-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmodel',
            old_name='sku',
            new_name='item',
        ),
    ]
